### ISSUE TITLE
USB Host shield support

### ISSUE THREAD

**Issue by SvOlli** [matsstaff/mwd2cdtv#1]
Hello!

I'm working on a similar project. The main difference is that my input is taken from a [USB Host shield](http://www.shop.tkjelectronics.dk/product_info.php?products_id=45) mounted on an Arduino Pro mini. Since this requires the Arduino Pro mini running on 3.3V, there are some things to consider, as it runs with only 8MHz. Still, keyboard is working now. I'm using your amiga_keyb and cdtv files for outputting my data.

For the implementation, I could either fork your project and add my work using #ifdefs or create a separate project. Since your code is the basis for my code, I think it's fair to make it your call.

Best wishes,
SvOlli

P.S.: I would have tried to contact you via mail, but the repo lacks any contact information.

**Comment by matsstaff** [comment]
Hi SvOlli! 

Nice! 
I've borrowed/reworked some code for the amiga keyboard myself. I think it is attributed. As for my code, feel free to use it in any way you want ;) 
Cheers! 
//mats

**Comment by SvOlli** [comment]
Okay. Then I think having a separate project with unmodified amiga_keyb and cdtv files would need the least maintenance.

But I'm still experiencing one problem: cdtv is hardcoded for a 16MHz ATmega. Could you add a "#define flag" to switch to 8MHz as well? I need this, because the USB Host shield needs to have the Arduino Pro micro switched to 3.3V. And this in places clocks the ATmega down to 8MHz.

Once I've got mouse support working, I only need to write up the readme to complete the release.

**Comment by matsstaff** [comment]
Well, the project in its entirety is written for 16MHz. While changing just the timing for 8MHz probably is pretty trivial, I have not got a setup like that, so I can't test it.
So, I'd suggest either you make the changes you want in your project **or** you could switch to use a 16MHz Pro Mini. You can still run it at 3.3v (it is out of spec, but many do so anyway with no issue).
Cheers! 
//mats

**Comment by SvOlli** [comment]
Going for a 3.3V 16Mhz is not really an option, as I want just to assemble standard components, and not modify them, since it's supposed to be an open project, not just a private one.

On the other hand, I can provide you with a 3.3V pro mini with USB shield for testing. Or you make the changes and I test them. Final option is I'll try to change it myself, a bit like the sorcerer's apprentice. 

Speaking of the sorcerer's apprentice approach: should changing the timing just be writing only half of the original values to OCR1A, or is there more to do? That didn't work for me, so I might be missing something.

Nevertheless, for debugging with a (still to borrow) logic analyser if things go wrong, I'd like to have a reference. I was thinking about your PS/2 mouse to CDTV adapter. Should that one work?

**Comment by SvOlli** [comment]
I got it working, well almost. First of all, my problem was using the pins of the wire were labelled incorrect.

Just using the half of the values written to OCR1A did the trick. Thanks for the support.

I am still having minor problems converting the mouse movements from USB to CDTV. When I accumulate the movements and send them in the main loop, moving up or left does not work as well as down or right. When I send the movements in the handler, the holding of a mouse button is "lost" and the button gets pressed again when I move the mouse again. Any idea?

Also, if you like, I could fix the 16MHz/8MHz problem in your code with an automatic detection using the F_CPU macro as a gate similar to the implementation of delayMicrosecond.

**Comment by matsstaff** [comment]
Hi!
Sorry for the late reply. 
Good that you've made progress! 
It is difficult to pinpoint what could be wrong, but my guess would be that communication is not following the protocol.
I'd use a DSO to look at what is going on.
Lost mouse button state, sounds like you aren't sending packets every ~32ms with the 'mouse button pressed' state.
Movement not working could be jitter or something else messing the protocol up (it is after all asynchronous). 
The code is not very optimized and some of the timings are pretty short. It could be an issue when running the MCU at half the freq.
Cheers!
//mats

**Comment by SvOlli** [comment]
Thanks! No sweat, we're all here for fun, aren't we?

I found a solution for the problem.
I update the CDTV package every main loop now and changed a little bit in mouse_set_state():
```
#if 0
  mouse_x = mouse_x - (mouse_x >> 1) + x; // Leaky integration
  mouse_y = mouse_y - (mouse_y >> 1) + y;
#else
  if( x == -1 ) x = -2;
  else if( x == +1 ) x = +2;
  if( y == -1 ) y = -2;
  else if( y == +1 ) y = +2;
  mouse_x = mouse_x + (x/2);
  mouse_y = mouse_y + (y/2);
#endif
```
I was first assuming to that the `>> 1` does not work well with negative numbers, so I tried it with `/ 2`. But that did also not work as I expected, so I decided to drop it completely. And things evolved a bit from there, and still will before the release.

So I'm happy with the current state now. Joystick should work, if it was working in your code. This is something that will test, once the first release of the project is completed.

**Comment by SvOlli** [comment]
So, my USB2Amiga is now online at https://github.com/SvOlli/USB2Amiga .
Thanks again for the help.

**Comment by matsstaff** [comment]
Nice! :)

**Comment by SvOlli** [comment]
Got another question: I want to send the CDTV_CODE_POWER command, but I can't find any function to send out any of those CDTV_CODE_* . Could it be that the routine has been optimized out by direct implementation of the mouse codes in the "TIMER1_COMPA_vect" handler?

**Comment by matsstaff** [comment]
In my project, I only send joystick state as 'IR coded'. But you could send any of the commands. It is all handled in timer 1. I have not implemented any generic function to send IR codes, but it should be pretty easy to do. Just look at how joystick is handled.
